GET http://localhost:8080/books

###
get http://localhost:8080/events

###
GET http://localhost:8080/ticketcategory

###
delete http://localhost:8080/events/6/delete

###
POST http://localhost:8080/events
Content-Type: application/json

{
    "eventName" : "fuck",
    "eventDescription": "me",
    "startDateTime": "09/11/2001",
    "venue": "world trade centre",
    "artist": "obama bin laden",
    "capacity": 100
}
###
POST http://localhost:8080/events/4/add
Content-Type: application/json

{
    "name": "Fucker",
    "price": 6.99,
    "eventId": 4
}

###
POST http://localhost:8080/ticketcategory/2/make-tickets?count=10
Content-Type: application/json

{
}