GET http://localhost:8080/books

###

DELETE http://localhost:8080/books/3

###
GET http://localhost:8080/events

###
GET http://localhost:8081/ticketcategory


###
POST http://localhost:8080/events
Content-Type: application/json

{
    "eventName" : "name1",
    "eventDescription": "me",
    "startDateTime": "09/11/2001",
    "venue": "world centre",
    "artist": "obama",
    "capacity": 100
}
###
POST http://localhost:8081/ticketcategory
Content-Type: application/json

{
    "name": "Faust",
    "price": 6.99,
    "eventId": 1
}